apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp-dep
 labels:
  type: back-end
spec:
 template:
  metadata:
   name: myapp
   labels:
    type: back-end
  spec:
   containers:
    - name: app-container
      image: krishnansai/new-sag:1.0
      env:
        - name: DB_HOST
          valueFrom:
           secretKeyRef:
             name: db-user-pass-id
             key: DB_HOST
        - name: DB_USER
          valueFrom:
           secretKeyRef:
             name: db-user-pass-id
             key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
           secretKeyRef:
             name: db-user-pass-id
             key: DB_PASSWORD
        - name: DB_DATABASE
          valueFrom:
           secretKeyRef:
             name: db-user-pass-id
             key: DB_DATABASE
        - name: DB_PORT
          valueFrom:
           secretKeyRef:
             name: db-user-pass-id
             key: DB_PORT
        - name: PORT
          valueFrom:
           secretKeyRef:
             name: db-user-pass-id
             key: PORT
 replicas: 1
 selector:
  matchLabels:
   type: back-end
---
apiVersion: v1
kind: Service
metadata:
  name: sag-back-src
spec:
  type: NodePort
  selector:
    type: back-end
  ports:
    - name: myapp
      port: 4000
      targetPort: 4000


